apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: master
  labels:
    service: ess
spec:
  serviceName: ess
  replicas: 3
  selector:
    matchLabels:
      service: ess
  template:
    metadata:
      labels:
        service: ess
    spec:
      
      initContainers:
      - name: volume-permission
        image: busybox
        command:
        - sh
        - -c
        - chown -R 1000:1000 /usr/share/elasticsearch/data
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      - name: vmmaxcount
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        env:
          - name: cluster.name
            value: elasticsearch-cluster
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          
          - name: node.master
            value: "true"
          - name: node.ingest
            value: "false"
          - name: node.data
            value: "false"
          - name: ES_JAVA_OPTS
            value: -Xms512m -Xmx512m
          - name: discovery.seed_hosts
            value: "elasticsearch"
          - name: network.host
            value: "_site_,_lo_"  
          - name: cluster.initial_master_nodes
            value: "master-0,master-1,master-2"
          
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: ssd
      resources:
        requests:
          storage: 3Gi
