apiVersion: v1
kind: Service
metadata:
  name: ess
  labels:
    service: ess
spec:
  clusterIP: None
  ports:
    - port: 9300
      name: transport
    - port: 9200
      name: http
  selector:
    service: ess
